breakPoints:
  com.example.Main:
  - !!com.hagenberg.jarvis.models.entities.BreakPoint
    className: com.example.Main
    enabled: true
    line: 29
    suspendPolicy: 2
  - !!com.hagenberg.jarvis.models.entities.BreakPoint
    className: com.example.Main
    enabled: true
    line: 19
    suspendPolicy: 2
  - !!com.hagenberg.jarvis.models.entities.BreakPoint
    className: com.example.Main
    enabled: true
    line: 28
    suspendPolicy: 2
classPath: C:\Users\chris\OneDrive\Arbeit\Studium\BachelorThesis\jarvis\programming\Evaluation\demo\target\classes
mainClass: com.example.Main
sourcePaths:
- C:\Users\chris\OneDrive\Arbeit\Studium\BachelorThesis\jarvis\programming\Evaluation\demo\src\main\java
specialClasses:
- java.lang.Class
- java.lang.invoke.DirectMethodHandle
- jdk.internal.*
transformers: {}
