breakPoints:
  swe4.Main:
  - !!com.hagenberg.jarvis.models.entities.BreakPoint
    className: swe4.Main
    enabled: true
    line: 37
classPath: C:\Users\chris\OneDrive\Arbeit\Studium\Semester4\SWE\Programming\HUE04\src\pathfinder\out\production\pathfinder
mainClass: swe4.Main
sourcePaths:
- java.lang.Class
specialClasses:
- java.lang.Class
- java.lang.invoke.DirectMethodHandle
transformers: {}
