breakPoints:
  com.hagenberg.debuggee.JDIExampleDebuggee:
  - !!com.hagenberg.jarvis.models.entities.BreakPoint
    className: com.hagenberg.debuggee.JDIExampleDebuggee
    enabled: true
    line: 30
  - !!com.hagenberg.jarvis.models.entities.BreakPoint
    className: com.hagenberg.debuggee.JDIExampleDebuggee
    enabled: true
    line: 33
  - !!com.hagenberg.jarvis.models.entities.BreakPoint
    className: com.hagenberg.debuggee.JDIExampleDebuggee
    enabled: true
    line: 35
transformers: {}
